services:
  proxy:
    image: ${PROXY_IMAGE}
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static
  
  app:
    image: ${APP_IMAGE}
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
  
volumes:
  static-data:
