services:
  frontend:
    build:
      context: ./frontend
    restart: always
    environment:
      - FRONTEND_PORT=3000
      - BACKEND_ADDRESS=http://backend:9000/
    depends_on:
      - backend
    ports:
      - 80:3000
  
  backend:
    build:
      context: ./backend
    restart: always
    environment:
      - BACKEND_PORT=9000
      - REDIS_HOST=redis
      - REDIS_PORT=7000
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_REBUILD=${DB_REBUILD}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - redis
      - db

  redis:
    image: redis:7.2.4-alpine
    restart: always
    volumes:
      - redis-data:/data
    command: >
      sh -c "echo \"port 7000\" > /usr/local/bin/redis.conf
             redis-server /usr/local/bin/redis.conf"
 
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  redis-data:
  postgres-data:
