services:
  frontend:
    image: ${FRONTEND_IMAGE}
    restart: always
    environment:
      - FRONTEND_PORT=3000
      - BACKEND_ADDRESS=http://backend:9000/
    depends_on:
      - backend
    ports:
      - 80:3000

  backend:
    image: ${BACKEND_IMAGE}
    restart: always
    environment:
      - BACKEND_PORT=9000
      - REDIS_HOST=redis
      - REDIS_PORT=7000
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_REBUILD=${DB_REBUILD}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - redis

  redis:
    image: redis:7.2.4-alpine
    restart: always
    volumes:
      - redis-data:/data
    command: >
      sh -c "echo \"port 7000\" > /usr/local/etc/redis/redis.conf
             redis-server /usr/local/etc/redis/redis.conf"

volumes:
  redis-data:
