services:
  frontend:
    image: ${FRONTEND_IMAGE}
    restart: always
    depends_on:
      - backend
    ports:
      - 80:8000
  
  backend:
    image: ${BACKEND_IMAGE}
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
