name: 'Build and Publish Workflow'

on:
  push:
    branches:
      'main'
  pull_request:
    branches:
      'main'
  workflow_dispatch:

jobs:
  build-and-publish-job:
    name: 'Build and Publish Job'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
    
      - name: 'Build Container Images'
        run: |
          docker build -f frontend/Dockerfile -t logic-graph-scalable-frontend:latest frontend/
          docker build -f backend/Dockerfile -t logic-graph-scalable-backend:latest backend/

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Push to GitHub Container Registry'
        run: |
          docker tag logic-graph-scalable-frontend:latest ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-frontend:latest
          docker tag logic-graph-scalable-backend:latest ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-backend:latest
          docker tag logic-graph-scalable-frontend:latest ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-frontend:${{ github.sha }}
          docker tag logic-graph-scalable-backend:latest ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-backend:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-frontend:latest
          docker push ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-frontend:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-backend:${{ github.sha }}
