name: 'Build and Publish Workflow'

on:
  push:
    branches:
      'main'
  pull_request:
    branches:
      'main'
  workflow_dispatch:

jobs:
  build-and-publish-job:
    name: 'Build and Publish Job'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
    
      - name: 'Build Container Images'
        run: |
          docker build -f app/Dockerfile -t logic-graph-scalable-app:latest app/
          docker build -f proxy/Dockerfile -t logic-graph-scalable-proxy:latest proxy/

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Push to GitHub Container Registry'
        run: |
          docker tag logic-graph-scalable-app:latest ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-app:latest
          docker tag logic-graph-scalable-proxy:latest ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-proxy:latest
          docker tag logic-graph-scalable-app:latest ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-app:${{ github.sha }}
          docker tag logic-graph-scalable-proxy:latest ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-proxy:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-app:latest
          docker push ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-proxy:latest
          docker push ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-app:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/logic-graph-scalable-proxy:${{ github.sha }}
