name: 'Staging Environment Creation'

# This workflow is triggered manually
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_staging:
    name: 'Create staging environment'
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Install Terraform'
      run: |
        wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update && sudo apt install terraform

    - name: 'Install Packer'
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install packer

    - name: 'Install Node.js'
      run: |
        curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs

    #- name: 'Build AMI'
    #  run: |
    #    cd infra/images
    #    packer build .
