name: 'Deploy'

on:
  push:
    branches:
      'main'
  pull_request:
    branches:
      'main'
  workflow_dispatch:

jobs:
  deploy-job:
    name: 'Deploy Job'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
    
      - name: 'Build Container Image'
        run: |
          cd deployable
          docker build -t lightsail-hello-world:latest .

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Push to GitHub Container Registry'
        run: |
          docker tag lightsail-hello-world:latest ghcr.io/${{ github.repository_owner }}/lightsail-hello-world:latest
          docker tag lightsail-hello-world:latest ghcr.io/${{ github.repository_owner }}/lightsail-hello-world:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/lightsail-hello-world:latest
          docker push ghcr.io/${{ github.repository_owner }}/lightsail-hello-world:${{ github.sha }}

      - name: 'Push Tutorial Container'
        run: aws lightsail push-container-image --service-name hello-world --label hello-world --image sebsto/lightsail-hello-world:latest
