name: Hi

on:
  push:
    branches:
      'main'
  pull_request:
    branches:
      'main'
  workflow_dispatch:

jobs:
  say_hi:
    name: 'Hello!'
    runs-on: ubuntu-latest

    steps:
      name: 'Print Hi'
      run: |
        echo Hello
        echo World
