name: 'Copy Tutorial Image'

### This file exists to copy the Docker Hub image for
### sebsto/lightsail-hello-world and to push it to 
### my GitHub Container Registry. This is to troubleshoot
### the AWS Lightsail manual deployment system, since I know
### that the tutorial image works while my images don't seem to.

on:
  workflow_dispatch:

jobs:
  copy-image:
    name: 'Copy Image'
    runs-on: ubuntu-latest

    steps:
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Pull and Push'
        run: |
          docker pull sebsto/lightsail-hello-world:latest
          docker tag sebsto/lightsail-hello-world:latest ghcr.io/${{ github.repository_owner }}/lightsail-hello-world:latest
          docker push ghcr.io/${{ github.repository_owner }}/lightsail-hello-world:latest
